### ISSUE TITLE
SQL issue

### ISSUE THREAD

**Issue by chandanak28** [hieusydo/Airline-Booking-System#8]
Hi. I'm trying to implement this and I'm having some issue with the sql part. Can you please help me with that.

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\__main__.py", line 14, in <module>
    main(as_module=True)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\cli.py", line 293, in __init__
    self._load_unlocked()
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\flask\cli.py", line 235, in locate_app
    __import__(module_name)
  File "C:\Users\Anjana\PycharmProjects\Airline-Reservation-System2\init.py", line 5, in <module>
    from appdef import app, conn
  File "C:\Users\Anjana\PycharmProjects\Airline-Reservation-System2\appdef.py", line 18, in <module>
    cursorclass=pymysql.cursors.DictCursor)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\pymysql\connections.py", line 327, in __init__
    self.connect()
  File "C:\Users\Anjana\Virtualenv\lib\site-packages\pymysql\connections.py", line 568, in connect
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: module 'socket' has no attribute 'AF_UNIX'

Process finished with exit code 1

This is error im currently getting. Please help me. 
Thank You

**Comment by hieusydo** [comment]
Seems like you are running the project on Windows, which is currently not supported.
